server :
  port : 8080
Spring:
  kafka :
    boostrap-servers : localhost:9092
    consumer :
      group-id : "my-awesome-app"

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: syspass
  driverClassName: org.postgresql.Driver

  Servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB

app:
  token:
    secret : m#MySecretGGWP2024
    issuer : BackendService
  email :
    from : phongsawattest99@gmail.com


