server:
  port: 8080
Spring:
  kafka:
    boostrap-servers: ${SECRET_KAFKA_HOST:localhost}:${SECRET_KAFKA_PORT:9092}
    consumer:
      group-id: "my-awesome-app"

  redis:
    host: ${SECRET_REDIS_HOST:localhost}
    port: ${SECRET_REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 300000

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    platform: postgres
    url: jdbc:postgresql://${SECRET_DB_HOST:localhost}:${SECRET_DB_PORT:5432}/postgres
    username: ${SECRET_DB_USERNAME:postgres}
    password: ${SECRET_DB_PASSWORD:syspass}
  driverClassName: org.postgresql.Driver

  Servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB

app:
  token:
    secret: ${SECRET_JWT_SECRET:'m#MySecretGGWP2024'}
    issuer: BackendService


